### ISSUE TITLE
Error with go 1.18

### ISSUE THREAD

**Issue by marcbria** [glycerine/xml2csv#1]
I tried to run your code with go version go1.18.1 linux/amd64 (the version included in ubuntu 22.04) and I got an error:

```
$ go run xml2csv.go -i ./ONIX-test.xml -o ./output.csv

# command-line-arguments
./xml2csv.go:132:2: undefined: panicOn
```

Any idea about how to fix this?

**Comment by glycerine** [comment]
include the other go file too.

the panicOn func is defined in vprint.go

I would do a go build first, then run the executable

**Comment by marcbria** [comment]
Sorry in advance for my lack of GO knowledge.

I just cloned your master branch and I did a "go build" but didn't help much:

```
go build 
go: cannot find main module, but found .git/config in ./xml2csv
	to create a module there, run:
	go mod init
```

If you could provide simple build/run instructions in your README it will probably help to avoid stupid questions like mines.

Thanks for your work,
m.

**Comment by glycerine** [comment]
why didn't you follow the prompt given? If you want to run with module mode on, then you'll need to make a module with 'go mod init'.  This is exactly what go build told you. This project does not require modules. So, turn modules off before compiling by setting env var GO111MODULE=off, or create a module with go mod init, run from within the directory holding the .go files.

**Comment by glycerine** [comment]
This is really a source code fragment project for coders. It is incomplete in many ways, and is not aimed at being a polished, consumer product.

**Comment by marcbria** [comment]
> why didn't you follow the prompt given? 

Because I don't know how a go program look like?
Sorry for the annoyance. No more questions from here.

On my discharge, to say that the previous line complained that "cannot find main module"... so I figured I couldn't do the mod without it.

> This is really a source code fragment project for coders. It is incomplete in many ways, and is not aimed at being a polished, consumer product.

Good to know. Thanks a lot for your time.
